# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nhqqLB6XeEX332axIK09nSDyn_Gq2OU
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import os

# --- PAGE CONFIG ---
st.set_page_config(
    page_title="Trader Sentiment Analysis Dashboard",
    page_icon="📊",
    layout="wide"
)

# --- DATA LOADING ---
@st.cache_data
def load_data():
    # Aapke GitHub screenshot ke according path 'Data/' folder mein hai
    file_path = 'Data/dashboard_data.csv'

    if not os.path.exists(file_path):
        return None

    df = pd.read_csv(file_path)
    if 'date' in df.columns:
        df['date'] = pd.to_datetime(df['date'])
    return df

# Initialize Data
df = load_data()

# --- ERROR HANDLING ---
if df is None:
    st.error("❌ **File Not Found:** `Data/dashboard_data.csv` nahi mili.")
    st.info("""
    **Checklist:**
    1. Kya aapne `dashboard_data.csv` ko `Data` naam ke folder mein dala hai?
    2. GitHub par folder ka naam 'Data' (Capital D) hai ya 'data' (Small d)? Code mein exact match hona chahiye.
    """)
    st.stop()

# --- SIDEBAR FILTERS ---
st.sidebar.header("Filter Settings")
sentiment_order = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
available_sentiment = [s for s in sentiment_order if s in df['classification'].unique()]

selected_sentiment = st.sidebar.multiselect(
    "Market Sentiment Phase:",
    options=available_sentiment,
    default=available_sentiment
)

filtered_df = df[df['classification'].isin(selected_sentiment)]

# --- HEADER ---
st.title("📈 Trader Behavior vs. Market Sentiment")
st.markdown(f"Showing analysis for {len(filtered_df)} data points.")

# --- KPI METRICS ---
m1, m2, m3, m4 = st.columns(4)
m1.metric("Avg Daily PnL", f"${filtered_df['daily_pnl'].mean():,.2f}")
m2.metric("Avg Leverage", f"{filtered_df['avg_leverage'].mean():.2f}x")
m3.metric("Total Trades", f"{int(filtered_df['trades_per_day'].sum()):,}")
m4.metric("Avg L/S Ratio", f"{filtered_df['long_short_ratio'].mean():.2f}")

st.divider()

# --- CHARTS ---
col1, col2 = st.columns(2)

with col1:
    st.subheader("Profitability Distribution")
    fig_pnl = px.box(
        filtered_df, x='classification', y='daily_pnl', color='classification',
        category_orders={"classification": sentiment_order},
        color_discrete_sequence=px.colors.diverging.RdYlGn
    )
    st.plotly_chart(fig_pnl, use_container_width=True)

with col2:
    st.subheader("Risk Appetite (Leverage)")
    fig_lev = px.violin(
        filtered_df, x='classification', y='avg_leverage', color='classification',
        box=True, category_orders={"classification": sentiment_order}
    )
    st.plotly_chart(fig_lev, use_container_width=True)

st.divider()

# --- REGRESSION SCATTER ---
st.subheader("Sentiment Score vs. Daily PnL")
fig_scatter = px.scatter(
    filtered_df, x='value', y='daily_pnl', color='classification',
    trendline="ols", labels={'value': 'Fear & Greed Score', 'daily_pnl': 'PnL ($)'}
)
st.plotly_chart(fig_scatter, use_container_width=True)

