# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nhqqLB6XeEX332axIK09nSDyn_Gq2OU
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Set professional page configuration
st.set_page_config(
    page_title="Hyperliquid Trader Behavior Dashboard",
    page_icon="📈",
    layout="wide"
)

# --- 1. Load Data ---
@st.cache_data
def load_data():
    # Ensure this filename matches exactly what you uploaded to GitHub
    df = pd.read_csv('dashboard_data.csv')
    df['date'] = pd.to_datetime(df['date'])
    return df

try:
    df = load_data()
except Exception as e:
    st.error(f"Error loading data: {e}")
    st.info("Ensure 'dashboard_data.csv' is in the root of your GitHub repository.")
    st.stop()

# --- 2. Sidebar Filters ---
st.sidebar.header("Filter Analytics")
sentiment_options = ['Extreme Fear', 'Fear', 'Neutral', 'Greed', 'Extreme Greed']
selected_sentiment = st.sidebar.multiselect(
    "Market Sentiment Phase:",
    options=sentiment_options,
    default=sentiment_options
)

# Filter dataframe based on selection
filtered_df = df[df['classification'].isin(selected_sentiment)]

# --- 3. Header Section ---
st.title("📈 Trader Performance vs. Market Sentiment")
st.markdown("""
This dashboard explores how retail trader behavior shifts during different psychological phases of the market.
Data sourced from **Hyperliquid Trade Logs** and aligned with the **Bitcoin Fear & Greed Index**.
""")

# --- 4. High-Level Metrics (KPIs) ---
col1, col2, col3, col4 = st.columns(4)

with col1:
    avg_pnl = filtered_df['daily_pnl'].mean()
    st.metric("Avg Daily PnL", f"${avg_pnl:,.2f}", delta=None)

with col2:
    avg_lev = filtered_df['avg_leverage'].mean()
    st.metric("Avg Leverage Used", f"{avg_lev:.2f}x")

with col3:
    total_trades = filtered_df['trades_per_day'].sum()
    st.metric("Total Executions", f"{int(total_trades):,}")

with col4:
    ls_ratio = filtered_df['long_short_ratio'].mean()
    st.metric("Avg L/S Ratio", f"{ls_ratio:.2f}")

st.divider()

# --- 5. Behavioral Visualizations ---
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Risk Appetite: Leverage vs. Sentiment")
    # Custom color map for sentiment
    color_map = {
        'Extreme Fear': '#d73027', 'Fear': '#f46d43',
        'Neutral': '#fee08b', 'Greed': '#66bd63',
        'Extreme Greed': '#1a9850'
    }
    fig_lev = px.box(
        filtered_df,
        x='classification',
        y='avg_leverage',
        color='classification',
        category_orders={"classification": sentiment_options},
        color_discrete_map=color_map,
        points=False # Hide outliers for cleaner look
    )
    st.plotly_chart(fig_lev, use_container_width=True)

with col_right:
    st.subheader("Platform Churn: Trade Frequency")
    freq_data = filtered_df.groupby('classification')['trades_per_day'].median().reindex(sentiment_order=sentiment_options).reset_index()
    fig_freq = px.bar(
        freq_data,
        x='classification',
        y='trades_per_day',
        color='classification',
        color_discrete_map=color_map,
        labels={'trades_per_day': 'Median Trades/Day'}
    )
    st.plotly_chart(fig_freq, use_container_width=True)

st.divider()

# --- 6. Sentiment Regression View ---
st.subheader("Correlation: Market Psychology vs. Profitability")
fig_scatter = px.scatter(
    filtered_df,
    x='value',
    y='daily_pnl',
    color='classification',
    hover_data=['Account', 'avg_leverage'],
    opacity=0.5,
    trendline="ols", # Adds a trendline to show relationship
    labels={'value': 'Fear & Greed Score (0-100)', 'daily_pnl': 'Daily PnL (USD)'}
)
fig_scatter.add_hline(y=0, line_dash="dash", line_color="white")
st.plotly_chart(fig_scatter, use_container_width=True)

st.caption("Built for Primetrade.ai Internship Evaluation | Candidate: Nitish Patel")

